 - name: user
   hosts: demo
   #vars_files:
   #- ./playbook-vars.yaml
   #vars_prompt:
   #- name: user
   #  prompt: "Введите пользователя"
   #  private: no
   tasks:
    - name: preconfig block
      block:
        - name: Create user
            user:
              #name: "{{user}}"
                name: "uutretretee"
                state: present
        - name: install curl
           apt:
             name: curl
             update-cache: yes
      become: true
      #register: out
      #- debug:
            #var: out