- name: preconfig
  hosts: demo
  #vars:
  #user: 'docker-user'
  tasks:
    - name: Установка docker
      block:
        - name: Добавляем universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ansible_distribution_release}} universe"
            state: present
          become: true

        - name: Установка доп пакетов
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
            update-cache: yes
            cache_valid_time: 86400
          become: true
        - name: добавление ключа docker
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            keyring: /etc/apt/keyrings/docker.gpg
            state: present
          become: true
        
        - name: Установка стабильного репозитория
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu
              {{ansible_distribution_release}} stable
            state: present
            update-cache: yes
            filename: docker
          debugger: on_failed
          become: true

        - name: Установка docker ce
          apt:
            name: docker-ce
            update-cache: yes
          become: true

        - name: Установка docker compose
          apt:
            name: docker-compose
            update-cache: yes
          become: true
        - name: Проверка установки Docker
          service:
            name: docker
            state: restarted
            enabled: yes

          become: true

    - name: Завершение установки

      block:
        - name: Создание группы
          group:
            name: docker
            state: present
          become: true

        - name: Создание пользователя  docker
          user:
            name: docker-user
            groups: docker
            append: yes

        - name: Перезагрузка сервера
          reboot:

      become: true